### ISSUE TITLE
Agreements should be versioned

### ISSUE THREAD

**Issue by calebissharp** [bcgov/range-api#103]
Agreements should be versioned to keep a history of changes to clients.

Planned changes:
- [ ] Add `version` column to `agreement` table
- [ ] When creating new plans, add it to the latest version of an agreement
- [ ] When a new version of an agreement is created, the current versions of any RUPs attached to the previous agreement should be updated to point to the new agreement.
- In FTA import
- [ ] Detect when a client's status has been changed for an agreement. If so, create new client_agreement and agreement records.

**Comment by micheal-w-wells** [comment]
lets do https://github.com/bcgov/range-api/issues/90 first

@calebissharp to upload pic to jog our memory

**Comment by calebissharp** [comment]
Closing because we decided to replace our versioning system with JSON snapshots.
