### ISSUE TITLE
import job does not calculate total non usage correctly

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-api#105]
should be adding    
"non_use_nonbillable": 0,
  "non_use_billable": 0

**Comment by calebissharp** [comment]
@LisaMoore1 I'm pinging you, in case you don't see the `range-api` issues.

**Comment by LisaMoore1** [comment]
@calebissharp @micheal-w-wells If I need to test this one I need to know which RANs to take a look at. Thx.

**Comment by micheal-w-wells** [comment]
Will do.  Rerunning as soon as our password is reset in dev/test.

**Comment by micheal-w-wells** [comment]
I've assigned the following test rans to you @LisaMoore1 Note test FTA is not the same as real FTA.  I'll slack ya the usage file to go along with these:
`
myra=# select forest_file_id from agreement where forest_file_id in (select agreement_id from ref_usage where total_non_use > 0 and year > 2020) and created_at
> '2020-01-15';
 forest_file_id
----------------
 RAN076006
 RAN075936
 RAN076336
 RAN071003
 RAN071140
 RAN071896
 RAN073105
 RAN073465
 RAN071112
 RAN076155
 RAN074264
 RAN073636
(12 rows)`

**Comment by micheal-w-wells** [comment]
@LisaMoore1 are we good to close this one? This code has been live for awhile
