### ISSUE TITLE
Set up daily automated backups of myrange db

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-api#109]
I've been taking weekly backups (its a very small chore) but a recent issue for Krista made me wish i had one from yesterday to do analysis.  Failed previously at setting up automated ones (openshift-foo was weak) but yesterday managed to get the backup app configured in prod.  Right now there is a 'storage freeze' (more specifically with the nfs-backup storage class).  Once that is resolved after the holidays I can turn on the backups with a few clicks and we will have them for every day,  which is not only better insurance but will aid with troubleshooting.

**Comment by micheal-w-wells** [comment]
they provided storage just need to carve out time to wrap this one up.

**Comment by calebissharp** [comment]
@micheal-w-wells Have you figured this out yet?
