### ISSUE TITLE
Plan status history is being lost when a new version is created

### ISSUE THREAD

**Issue by calebissharp** [bcgov/range-api#123]
The plan status history is attached to the plan's id, and references the oldest version of a plan, even after a new version of the plan is created with a different ID. Possible solutions are to reference the canonical ID of the plan instead, or version the `plan_status_history` table.

**Comment by calebissharp** [comment]
@LisaMoore1 Is this still an issue? I haven't noticed any weird behaviour with the status history for a while, but I wanted to check with you first.

**Comment by LisaMoore1** [comment]
@calebissharp I haven’t noticed it being an issue. I’ll keep my eye open but it can probably be closed now.

**Comment by calebissharp** [comment]
@LisaMoore1 Sweet, thanks.
