### ISSUE TITLE
DB Trigger:  On client_agreement create and delete ---> create and delete plan_confirmation record

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-api#159]
Issue summary (Skip to bottom of issue for steps to test). 

When no longer relevant client agreements are deleted, the plan confirmation record needs to get cleaned up.  Additionally, when clients are changed after the plan is created, they need to be created in plan_confirmation as well.

**Comment by micheal-w-wells** [comment]
- Only fire if there is a plan for that `agreement_id`
- Make sure to get the most recent plan if there are dupes
- `client_agreement on create`  makes appropriate `plan_confirmation` record for given clients.
- `client_agreement on delete` deletes appropriate `plan_confirmation` record for given clients.

**Comment by calebissharp** [comment]
@micheal-w-wells Would it be possible to just add a `plan_confirmed` column to `client_agreement` instead? And remove the `plan_confirmation` table? Since we won't have more than 1 plan per agreement now.

**Comment by micheal-w-wells** [comment]
@calebissharp that sounds pretty good, as long as we have a dedicated column for tracking the date signed rather than going off changed date on the table (there's a job that touches those regularly).

**Comment by calebissharp** [comment]
Hmm that's a good point. Doable though. Any other gotchas you can think of? As far as I can think, it's just a one-to-one relationship.

**Comment by micheal-w-wells** [comment]
Not necessarily a gotcha but very related is the need to notify staff that there are more people to sign the RUP.

**Comment by calebissharp** [comment]
Notifications will be another beast altogether, regardless of how the actual submissions are tracked.

**Comment by micheal-w-wells** [comment]
Resizing to reflect reality.  Also despite chatter here Caleb and I decided it would make sense with the time we have to just go the db trigger route.

**Comment by micheal-w-wells** [comment]
Requires running FTA synch in TEST.  Steps (and a place to track) for testing:

1. Create or find a RUP with a client or two on it.  
2. Change who is linked on it <--client + location + RAN. link in FTA, not user. <> BCEID linking.
3. Agreement signature shakedown:
    - [ ] You should get the right number of AH awaiting signatures
    - [ ] The AH should be able to complete 
    - [ ] Their signatures, pending and finished, should look right on web
    - [ ] Their signatures, pending and finished, should look right on pdf
    - [ ] Bonus/resiliency test: change who is linked again and see if signatures make sense.

We can use this as a cheat sheet when we beef up our UI testing also.

**Comment by micheal-w-wells** [comment]
@LisaMoore1 @ZoeSimon can probably hold off testing this until Caleb's client linking changes come in, then we can test it all in one shot.

**Comment by LisaMoore1** [comment]
@micheal-w-wells Can we move this to in progress until it is ready to test so that only things that need action “today” are in Review/QA?

**Comment by micheal-w-wells** [comment]
@LisaMoore1 I have very high confidence this works as I've tested it lots myself and I have been using the SQL to fix the ones that pop up in metabase.  Because this is a database only change, i realized I could apply it to prod ahead of time.  I've done so, as well as fix the remaining ones that we got alerted about on the weekend.  As this is all done I'm going to close it.
