### ISSUE TITLE
Hide amendment buttons for versioning fix release

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-api#163]

**Comment by micheal-w-wells** [comment]
@calebissharp I haven't looked at git so I don't know how hard it would be to throw all amendment stuff in a branch and pop off from dev, but I'm assuming it would be a PIA as its been a WIP for awhile.  I'm cool with just commenting them out for this week if that works for you.

**Comment by calebissharp** [comment]
@micheal-w-wells I don't think it makes sense to remove all the amendment implementation right now (it's also been partially implemented since the previous contractors anyways), so just hiding the button seems like the best solution.

**Comment by micheal-w-wells** [comment]
@LisaMoore1 @ZoeSimon I'm going to move all the amendment stuff in QA over to ice box while we work on this `versioning & client linking + misc fixes` release.
