### ISSUE TITLE
Add event and user_id to plan_snapshot.

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-api#164]
![image](https://user-images.githubusercontent.com/955467/78408107-1d5a1b00-75bb-11ea-88cf-218856e2fd6e.png)
Note on the diagram I'm not sure about the first couple AH statuses codes there, but the rest LGTM.

To potentially support UI functions and my own well being in the long haul, I want us to add `event` and `user` to `plan_snapshot`.

I'm not concerned with a migration to back populate right away (unless its really small effort).  What is important is that moving forward a RUP that goes through the usual workflow like @LisaMoore1 's colourful diagram looks like this in plan snapshot:

          `event`            `user_id`                 
`Staff Draft Submitted to AH.`     -     `Lisa`  NOTE: Lisa is stuck on this version while AH works
`Submitted for Feedback`            -     `AH 1`            NOTE: H1 is stuck on this one, and now Lisa see's this one
`Staff provide feedback`               -   `Lisa `            NOTE Staff now stuck on this one while AH has edit.

... and so on.

@calebissharp have a gander

**Comment by calebissharp** [comment]
How do we determine what to send for `event`? Is it just a string column? As well, what advantages would this provide over the existing status history we have with `plan_status_history`?

`user` should be fairly straightforward to implement on the backend.

**Comment by micheal-w-wells** [comment]
I guess the question is, is there a new row in `plan_status_history` for every row of `plan_snapshot` in all cases?   If yes then we're good its just writing the query, if not then we need to address it in one table or the other so I have a complete picture when troubleshooting.  If we can get it from `plan_status_history` a computed column on `plan_snapshot` would still be useful for me.

**Comment by calebissharp** [comment]
@micheal-w-wells Yep, I think we can safely assume that whoever has the latest entry in `plan_status_history` was the latest person to take action and therefore the latest person to create a version, whether we're just snapshotting on amendment creation or every status change. The only tricky thing will be if you want to snapshot on every save.

**Comment by micheal-w-wells** [comment]
@calebissharp yep that's the tricky part, I'm interested in getting my query/view to work.  I think an undo button for drafts would be pretty sweet, and any prod form problems are likely going to be in draft so its extra logging for me down the road.  If i can't get it done today/this weekend or decide its futile my plan is to go back to `plan_status_history` and not snapping drafts.

**Comment by micheal-w-wells** [comment]
I think we have the bases covered with #167 , closing.

**Comment by micheal-w-wells** [comment]
note to self i put the label there because it has the picture
