### ISSUE TITLE
Version endpoint test not passing due to additional fields

### ISSUE THREAD

**Issue by calebissharp** [bcgov/range-api#175]
@micheal-w-wells Looks like most of the version tests were actually being skipped; that's my bad. This led to some false positives when developing the additional information for the version endpoint. Are you able to resolve the failing tests at some point? It shouldn't be too tricky to do, we just need to add the missing fields to what the test expects the endpoint to return.

**Comment by micheal-w-wells** [comment]
Yep works for me

**Comment by calebissharp** [comment]
@micheal-w-wells Awesome, thanks. I should add that this should be fixed as soon as you have time, since it's going to throw off other PRs we open.

**Comment by calebissharp** [comment]
@micheal-w-wells If you haven't already started, I'm going to take a shot at this.
