### ISSUE TITLE
Back end changes to allow user to see what kind of amendment each legal version is from

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-api#203]
dev summary:  add 'version_reason' to 'plan_snapshot_summary' 

In order for the UI to display where a legal version came from (initial RUP, amendment, etc) we would need to add this to the versions endpoint.  The easiest way to do this I'm hoping is to add another computed column to the plan_snapshot_summary table.

I think with the queries that are there now, it should be relatively straightforward to associate all the versions (draft etc) to each appropriate legal version.  I'll call that CTE 'legal_version_association' or something.

If that view existed, I would then look within it for:

**Group A:** For an initial RUP, I need to look for at least 1 version in a status of 6 with amendment type null and it is not in Group B, C, or D.

**Group B:** For a staff mandatory, I need to look for at least 1 version in a status of 22 

**Group C:**   For an AH minor, I need to look for at least 1 version in a status of 23 with amendment type ____ and not in Group B.

**Group D:**  For an AH major, I need to look for at least 1 version in a status of 23 with amendment type ____. 

@calebissharp its a bit closer i'm just stuck on a couple

**Comment by micheal-w-wells** [comment]
@calebissharp do you know the answers to this mad lib?

**Comment by calebissharp** [comment]
Won't the amendment types just be minor and mandatory for C and D, respectively?

**Comment by micheal-w-wells** [comment]
I didn't know if you gave em numbers or not that code is all new to me.  Also wondering is there a workflow where a ah minor beccomes a staff mandatory?  in that case is there a good way to split up group B

**Comment by calebissharp** [comment]
Checkout `ref_amendment_type`

**Comment by calebissharp** [comment]
Also yep, the PR I just opened adds the "Submit as Mandatory" option, which changes a minor amendment to mandatory.

**Comment by micheal-w-wells** [comment]
sweet ok i dont think this is going to be that bad then

**Comment by micheal-w-wells** [comment]
Going to close the api issue as its done and there's nothing for the user to test until range-web 789 referenced above (that uses it) is done
