### ISSUE TITLE
discarded amendment did not get marked as such in db

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-api#218]
@calebissharp the first staff minor in this list was discarded but did not get marked as such:

```
yra=# select id, version, status_id, is_discarded from plan_snapshot where plan_id = 219;
 id  | version | status_id | is_discarded
-----+---------+-----------+--------------
 269 |       1 |         6 | f
 270 |       2 |         1 | f
 271 |       3 |        18 | f
 272 |       4 |        14 | f
 273 |       5 |        15 | f
 274 |       6 |        12 | f
 275 |       7 |        22 | f
 276 |       8 |         1 | f
 277 |       9 |        18 | f
 278 |      10 |        14 | f
 279 |      11 |        15 | f
 280 |      12 |        12 | f
 281 |      13 |        23 | f
 282 |      14 |        18 | f
 283 |      15 |        21 | f
 284 |      16 |        18 | f
 285 |      17 |        21 | f
 286 |      18 |         9 | f
(18 rows)
```

**Comment by calebissharp** [comment]
@micheal-w-wells I don't see the one that was discarded? That first staff mandatory amendment looks like it made it to approved, and the AH minor amendment after that looked like it went to stands.

> the first staff minor in this list was discarded but did not get marked as such:

Only AHs can submit minor amendments. All amendments by staff are mandatory. Assuming you mean staff mandatory, I can't see a discarded one here anyway.

**Comment by micheal-w-wells** [comment]
my bad i meant that the ah minor didn't get discarded, or i lost count of how many i made, I'll try another today
