### ISSUE TITLE
Range Use Plan versioning

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-api#56]
Range use plans are living documents and knowing what state they were in at any point time is going to be important moving forward.  Locking down past versions from erroneous updates (like the FTA data push) will be critical as well.

It looks like versioning was at least thought about during dev and when you update a plan record its id changes (which is odd).  Could be that a new record is getting created and the old one purged.  A better solution will be to add a version column to both the plan object and its children.  Some data duplication is expected but given the small data sets we are dealing with it's a non issue.

This issue is to track the work on adding versioning to the api, there will be separate issues for range-web and range-ios.

**Comment by LisaMoore1** [comment]
@calebissharp @micheal-w-wells Is this part of the versioning work we are working this sprint? If so can one of you move it to sprint backlog?

**Comment by LisaMoore1** [comment]
@calebissharp Is there anything I should be doing to support this?

**Comment by calebissharp** [comment]
@LisaMoore1 Other than the usual frontend testing to make sure everything is still working, I don't think so. I've also noticed a few bugs in endpoints that I've gone in and fixed to resolve some of the frontend issues.

**Comment by calebissharp** [comment]
@LisaMoore1 and @micheal-w-wells I'm going to leave this open until we're sure the JSON snapshots are capturing everything we need, but I think this is probably resolved.

**Comment by micheal-w-wells** [comment]
lets include:

legal status - last action / who put it there
date range it was legal

**Comment by micheal-w-wells** [comment]
Closing as this was broken into a number of related issues that have been addressed.
