### ISSUE TITLE
API tests failing in PR check

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-api#67]
I added the same kind of PR check to run tests as we have on web, as some kind of setp forward to automating security vulnerability PR's once we have more tests.

Right now its failing though:  https://github.com/bcgov/range-api/runs/265784212

@calebissharp do you think this is specific to the run time env?

**Comment by calebissharp** [comment]
@micheal-w-wells Yep definitely. The tests will need the same environment as when you run them locally, like the test DB. You'll have to figure out some way to get that running in github actions, if there's a way to do that.

**Comment by micheal-w-wells** [comment]
It's interesting that the agreement route tests are ok but the rest fail.  Looks like same things failing in openshift, so fix will be the same here and there i'd imagine.

**Comment by calebissharp** [comment]
Resolved by #114
