### ISSUE TITLE
EDIT:   Address lack of loc code in plan confirmation

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-api#86]
During FTA synch outage, a number of RUPs were created with wrong client pointers, leading up to incorrect client_id getting set in plan_confirmation.

**Comment by micheal-w-wells** [comment]
@LisaMoore1 the same list of client id's applies to this one.  If those all look stale (and particularly like we shouldn't be waiting on a signature from them) then I can clear these out.

Marking as 'ready to test' but again its more of a 'spot check data'

**Comment by micheal-w-wells** [comment]
Unfortunately, to just clear these out based on the client id (and not location code), is a bit troublesome.  

If there are any plan confirmation records with client ids that aren't pulled down from FTA every day we can safely clear those out (that last list I sent would be my reference for doing so).  It's those that do exist in both lists (current and plan confirmation), that we are unsure about because of the missing location code in plan confirmation, so we'll need an issue to tackle that database issue.

**Comment by micheal-w-wells** [comment]
leaving ready to test as there's still a number of records we can clear up once lisa has had a chance to review the stale client list.

**Comment by LisaMoore1** [comment]
@micheal-w-wells When you are satisfied with this one can you please close it? Thx
