### ISSUE TITLE
Location code shouldn't be displayed when choosing client to link in Manage Clients.

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-api#88]
AH may have multiple location codes for their client number, and in order for them to see all their agreements we shouldn't link their BCEID to a single location code.

**Comment by micheal-w-wells** [comment]
It isn't, location code is just displayed when we pull up the list of clients in the manage client page.  Renaming issue to reflect the problem.

A separate but very related issue is making sure a list of distinct client numbers is displayed (once ref_client has all locations) is the only follow up to this one.

**Comment by calebissharp** [comment]
Closing in favour of https://github.com/bcgov/range-web/issues/418, since this is a frontend bug.
