### ISSUE TITLE
Only one record in ref_client for clients regardless of how many loc codes they have

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-api#89]
Only a single client record ends up in ref_client despite AH having multiple location codes for a given client number.

**Comment by micheal-w-wells** [comment]
https://github.com/bcgov/range-api/blob/28a3fef275c9cd1da7123efab220fd0131f7d3b9/scripts/import.js#L403 I think is why there's only one record per client

**Comment by micheal-w-wells** [comment]
@LisaMoore1 I'm thinking the best way to test this one is to run the import job in test again,  and export the records in client ref to check against FTA.

**Comment by LisaMoore1** [comment]
@micheal-w-wells Any updates/suggestions for test on this (and related ones)?

**Comment by micheal-w-wells** [comment]
Sort of a tough one I don't have any examples from FTA but can say with certainty that for every client, the same record was getting overwritten in no particular order and landing a random location code in our import job.  This change was merged in some time ago (actually in another PR than the referenced one) so its been regression tested a few times already,  I'd say you are safe to close it.
