### ISSUE TITLE
client tables in myrange poorly linked

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-api#90]
No way to know in client_agreement which client + loc should be there.

Should have a unique key for client + loc records if each of those is an 'FTA record'.

**Comment by micheal-w-wells** [comment]
@LisaMoore1 do client + loc codes get recycled? or are they only ever associated to one RAN ever?

**Comment by LisaMoore1** [comment]
@micheal-w-wells Client+loc combination only ever applies to specific client doing business either on their own or with specific joint venture partners. Example:
12345678-00 Lisa on her own (-00 is almost always the person/business on their own)
12345678-01 Lisa with Mike as a JV partner in DND
12345678-02 Lisa with mike as a JV partner in DSS

The 8 digits always refers to the individual/business and the location code reflects things like JVs, business relationship, if they have multiple offices in different towns  etc. The CLIENT application manages the relationships (i.e. every person in a partnership has their own Client-loc and those are linked in CLIENT. Client # generally applies to that person for their entire life and the the locations are used to reflect changing business relationships over time.

Staff person selects the primary contact in FTA and FTA looks to Client and pulls in the appropriate JV partners (recording their client-loc) based on the client-loc of the primary contact. A client may hold several RANs using a specific client-loc OR they may have RANs using several different location codes  but their client# would would be associated with all of those RANs.

**Comment by micheal-w-wells** [comment]
ok that helps a lot thank you!!

**Comment by micheal-w-wells** [comment]
is there any other field other than the RAN # itself that links two clients together on a venture?

**Comment by LisaMoore1** [comment]
@micheal-w-wells I'm not sure I completely understand the question but I think that is accurate. The RAN will be associated with the multiple clients that FTA added because of the primary's Client#-locn.  I think the only place we pull client info is as it relates to the RAN.

When we add agency agreements we will end up in a situation where a client wants a different agent associated with each of their locations. An example would be business with multiple locn codes and a different ranch manager associated with each. They will want to authorize the appropriate ranch manager to be able to sign for the correct RAN.

**Comment by micheal-w-wells** [comment]
Carrying the agency agreement thinking forward here, do each of those agents have their own client (and maybe location) code?  How to identify regular agreement holder vs agent?

**Comment by micheal-w-wells** [comment]
@calebissharp i'm thinking computed column that is 12345-12 (client + loc) so its easy to read and we'll call it client_location_id.  We'll add it to ref_client, as well as client agreement and plan confirmation.  The task then will be to track down the code that puts client records in client_agreement and plan_confirmation and make sure that its getting the right records also.  This making sense to you also?  Any other ideas?

**Comment by LisaMoore1** [comment]
@micheal-w-wells Couple other comments. Not all agents will have client #s or location codes (ex. the ranch manager who is acting as an agent for the company for that specific RAN). Both AH and their agent will need to be able to view, edit and sign for the relevant RANs. 

When fully developed agency agreements:
- have a time bound nature (expires on specific date after which agent no longer has access/authority)
- be cancelled by the AH at any time (the agent no longer has authority)
- need to be visible to staff (either displayed somewhere on the RUP or an option to view) summary of information (who, when, and how to contact)

Definitely something for us to dig into more in the new year.

**Comment by micheal-w-wells** [comment]
@calebissharp can I get a knex migrations primer?  I can manually run SQL to do this easily enough but if we are trying to keep things consistent I'll do it that way.

**Comment by micheal-w-wells** [comment]
maybe tomorrow morning we can crush this one together

**Comment by LisaMoore1** [comment]
@micheal-w-wells when you draft up some sort of plan for the relationship for this data can I have a look?

**Comment by calebissharp** [comment]
@micheal-w-wells Yeah, I can go over it with you tomorrow morning. The gist of it is that you run `knex migrate:make name-of-migration` and edit the file it creates. You can also just use the `knex.raw()` function to directly execute SQL if you don't want to use the DSL syntax. `src/libs/db2/migrations/20191023143720_create-plan-version.js` is a good example.

**Comment by LisaMoore1** [comment]
@micheal-w-wells  My main interest is confirming that our data model (or querying) accurately captures the relationship between CLIENT+locn and RAN in a way that is accurate (and hopefully accommodating). How we arrives there is magic to me.

**Comment by micheal-w-wells** [comment]
What we spitballed this morning is another ID column on ref_client, that uniquely identifies a client + loc code at a point in time (e.g., client 1234 loc 2 at status A).  That ID is what gets associated to the versioned RUP,  and in that way even if the client changes from status A to P,  the RUP keeps what was there.  Should new RUPs be created they should get the newest client + loc + status associated to that RAN.

We are still flushing out what needs to happen with client_agreement and plan_confirmation.  I think the easiest is to add a new ID column and point to the ID mentioned above.

**Comment by micheal-w-wells** [comment]
![image](https://user-images.githubusercontent.com/955467/71218874-0a277780-2278-11ea-870a-cebe05269d43.png)

**Comment by micheal-w-wells** [comment]
done in #110
