### ISSUE TITLE
Schedule clone

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-api#97]
Some range officers requesting ability to clone schedule forward to next year, guts to go in range-api and a button for web.

In interim can run this SQL for them:   (to be pasted here, only part of this getting done sprint 4 to save time on manual updates)

**Comment by calebissharp** [comment]
@micheal-w-wells This exists already, no? You are able to copy schedules into another year.

**Comment by micheal-w-wells** [comment]
ah so it must have been a state thing @calebissharp (wasn't in draft but they wanted it copied).  I thought this was an ipad only thing still.

thanks for the correction

**Comment by calebissharp** [comment]
@micheal-w-wells Yeah, that would make sense. As well, it's only agreement holders that can copy schedules. Is this something the range officers want to be able to do themselves though?

**Comment by micheal-w-wells** [comment]
@calebissharp yes it was staff asking for it, I think that opening up this feature to staff would be appreciated.

**Comment by calebissharp** [comment]
Closing in favour of https://github.com/bcgov/range-web/issues/400, since this is no longer an API issue.
